# Generated by Django 3.0.5 on 2020-04-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailtemplates',
            name='content_en',
            field=models.TextField(help_text='Content', null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='mailtemplates',
            name='content_ru',
            field=models.TextField(help_text='Content', null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='mailtemplates',
            name='title_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mailtemplates',
            name='title_ru',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
