# Generated by Django 3.0.5 on 2020-04-02 16:10

from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed', '0001_initial'),
        ('account', '0002_auto_20200402_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', image_cropping.fields.ImageCropField(blank=True, upload_to='user_photo')),
                ('cropping_port', image_cropping.fields.ImageRatioField('image', '150x200', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping port')),
                ('cropping_land', image_cropping.fields.ImageRatioField('image', '200x112', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping land')),
                ('cropping_square', image_cropping.fields.ImageRatioField('image', '100x100', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping square')),
                ('croppos_port', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('croppos_land', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('croppos_square', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('video', models.FileField(blank=True, upload_to='user_video')),
                ('duration', models.CharField(blank=True, max_length=30, null=True)),
                ('type_media', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=5, verbose_name='Type of media')),
                ('role_media', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('buffer', 'Buffer')], default='public', max_length=10, verbose_name='Role of media')),
                ('orient', models.CharField(choices=[('land', 'Landscape'), ('port', 'Portrait')], default='port', max_length=5, verbose_name='Orientation')),
                ('is_main', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('geolocation', models.CharField(max_length=250)),
                ('feed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedmedia', to='feed.UserFeed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
