# Generated by Django 3.0.5 on 2020-04-02 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_auto_20200402_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('has_video', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('geo', models.CharField(max_length=50)),
                ('lon', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('city', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_destination', to='account.UserProfile')),
                ('user_subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriber', to='account.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedcomment', to='feed.UserFeed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
