# Generated by Django 3.0.5 on 2020-04-02 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermedia', '0001_initial'),
        ('account', '0002_auto_20200402_1610'),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeed',
            name='last_media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lastmedia', to='usermedia.UserMedia'),
        ),
        migrations.AddField(
            model_name='userfeed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='userfeedsubscription',
            unique_together={('user_subscriber', 'user_destination')},
        ),
    ]
