# Generated by Django 3.0.5 on 2020-04-02 15:48

from decimal import Decimal
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('about_me', models.TextField(help_text='About me', verbose_name='About me')),
                ('language', models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], default='en', max_length=2, verbose_name='Language')),
                ('gender', models.CharField(choices=[('male', 'Man'), ('female', 'Woman')], db_index=True, default='male', max_length=6, verbose_name='Gender')),
                ('publicname', models.CharField(default='', max_length=250)),
                ('lastname', models.CharField(default='', max_length=250)),
                ('account', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('lookingfor', models.TextField(default='')),
                ('goal', models.TextField(default='')),
                ('job', models.TextField(default='')),
                ('city', models.CharField(default='', max_length=250)),
                ('country', django_countries.fields.CountryField(default='UA', max_length=2)),
                ('zodiac', models.CharField(default='', max_length=50)),
                ('is_camera', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_online', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
