# Generated by Django 3.0.5 on 2020-04-02 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200402_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginWarningHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_ok_ip_address', models.GenericIPAddressField()),
                ('current_warning_ip_address', models.GenericIPAddressField()),
                ('current_country', models.CharField(max_length=250)),
                ('current_city', models.CharField(blank=True, max_length=250)),
                ('full_current_location_info', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile')),
            ],
        ),
    ]
