# Generated by Django 3.0.5 on 2020-04-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_replenishmentlog_resetpasswordtoken_userprofiledoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about_me',
            field=models.TextField(default=''),
        ),
    ]
