# Generated by Django 3.0.5 on 2020-04-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useronline',
            name='gender',
            field=models.CharField(db_index=True, default='male', max_length=6),
            preserve_default=False,
        ),
    ]
