# Generated by Django 3.0.5 on 2020-04-06 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_replenishmentlog_resetpasswordtoken_userprofiledoc'),
        ('online', '0002_useronline_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useronline',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile'),
        ),
    ]
